In [ ]:
import pandas as pd
import FinanceDataReader as fdr

In [ ]:
x=  pd.read_excel('2026-01-26_corp_list.xlsx')

In [19]:
y = pd.read_excel('2026-01-23_etf_list.xlsx')

In [32]:
merged_df = pd.merge(x, y, on='Ticker', how='left')

In [33]:
merged_df.dropna(inplace=True)

In [34]:
merged_df.reset_index(inplace=True)

In [39]:
merged_df = merged_df[['Ticker','Name_x']]

In [49]:
merged_df[200:230]

     Ticker         Name_x
200  252000  TIGER 200동일가중

In [18]:
corp_name = x[['기업 이름']]

KeyError: "None of [Index(['기업 이름'], dtype='str')] are in the [columns]"

In [4]:
mon,tue,wed,thu,fri = x.columns[0],x.columns[2],x.columns[4],x.columns[6],x.columns[8]

In [5]:
p = x.iloc[1:,1:11:2]
p.columns = [mon,tue,wed,thu,fri]

In [6]:
result = {}
for i in corp_name['기업 이름']:
    present_dates = p.columns[p.isin([i]).any()].tolist()
    result[i] = present_dates

In [7]:
summary = {}

for corp,dates in result.items():
    first_date = min(dates) # 처음 나타난 날짜
    last_date = max(dates)  # 마지막으로 나타난 날짜

    summary[corp] = {
        'First': first_date.date(), 
        'Last': last_date.date(),
        'Duration': (last_date - first_date).days + 1  # 등장 기간(일수)
    }
summary_df = pd.DataFrame(summary).T

In [ ]:
# df_etfs = fdr.StockListing('ETF/KR')

In [10]:
df_corp = fdr.StockListing('KRX')

In [14]:
target_date = pd.to_datetime('2026-01-22').date()
target_date2 = pd.to_datetime('2026-01-23').date()
# new_on_20 = summary_df.loc[summary_df['First'] == target_date2]
new_on_20 = summary_df.loc[(summary_df['First'] == target_date) & (summary_df['Duration'] == 2)]
# new_on_20.columns = ['Name','First','Last','Duration']
new_on_20.reset_index(inplace=True)
new_on_20.columns = ['Name','First','Last','Duration']

In [15]:
merged_df = pd.merge(new_on_20, df_corp[['Code', 'Name']], on='Name', how='left')

In [16]:
merged_df

          Name       First        Last Duration    Code
0     LG에너지솔루션  2026-01-22  2026-01-23        2  373220
1         LG화학  2026-01-22  2026-01-23        2  051910
2       우리금융지주  2026-01-22  2026-01-23        2  316140
3      SK이노베이션  2026-01-22  2026-01-23        2  096770
4         삼양식품  2026-01-22  2026-01-23        2  003230
5       아모레퍼시픽  2026-01-22  2026-01-23        2  090430
6      BNK금융지주  2026-01-22  2026-01-23        2  138930
7         엘앤에프  2026-01-22  2026-01-23        2  066970
8         현대제철  2026-01-22  2026-01-23        2  004020
9       LG생활건강  2026-01-22  2026-01-23        2  051900
10      한국가스공사  2026-01-22  2026-01-23        2  036460
11         이마트  2026-01-22  2026-01-23        2  139480
12  SK아이이테크놀로지  2026-01-22  2026-01-23        2  361610
13       달바글로벌  2026-01-22  2026-01-23        2  483650
14        한국콜마  2026-01-22  2026-01-23        2  161890
15      코스모신소재  2026-01-22  2026-01-23        2  005070
16       LG화학우  2026-01-22  2026-01-23        2  051915
17        롯데칠성  2026-01-22  2026-01-23        2  005300
18       롯데웰푸드  2026-01-22  2026-01-23        2  280360
19    NICE평가정보  2026-01-22  2026-01-23        2  030190
20          후성  2026-01-22  2026-01-23        2  093370
21      동원시스템즈  2026-01-22  2026-01-23        2  014820
22         솔루엠  2026-01-22  2026-01-23        2  248070
23     솔루스첨단소재  2026-01-22  2026-01-23        2  336370
24     아모레퍼시픽우  2026-01-22  2026-01-23        2  090435
25       애경케미칼  2026-01-22  2026-01-23        2  161000
26    신세계인터내셔날  2026-01-22  2026-01-23        2  031430
27       TCC스틸  2026-01-22  2026-01-23        2  002710
28       삼아알미늄  2026-01-22  2026-01-23        2  006110
29        서울가스  2026-01-22  2026-01-23        2  017390
30       아세아제지  2026-01-22  2026-01-23        2  002310
31        사조산업  2026-01-22  2026-01-23        2  007160
32       JW홀딩스  2026-01-22  2026-01-23        2  096760
33         TYM  2026-01-22  2026-01-23        2  002900
34        삼영전자  2026-01-22  2026-01-23        2  005680
35        이연제약  2026-01-22  2026-01-23        2  102460
36        화승인더  2026-01-22  2026-01-23        2  006060
37       일진다이아  2026-01-22  2026-01-23        2  081000
38        한일철강  2026-01-22  2026-01-23        2  002220
39        대영포장  2026-01-22  2026-01-23        2  014160
40        진양산업  2026-01-22  2026-01-23        2  003780
41       신송홀딩스  2026-01-22  2026-01-23        2  006880
42          덕성  2026-01-22  2026-01-23        2  004830
43       씨아이테크  2026-01-22  2026-01-23        2  004920
44        진양화학  2026-01-22  2026-01-23        2  051630
45          영흥  2026-01-22  2026-01-23        2  012160
46          신풍  2026-01-22  2026-01-23        2  002870
47        진양폴리  2026-01-22  2026-01-23        2  010640